// Mock data for donors
export const mockDonors = [
    {
        id: '1',
        name: 'Rajesh Kumar',
        age: 28,
        gender: 'Male',
        bloodGroup: 'O+',
        phone: '9876543210',
        email: 'rajesh.kumar@email.com',
        address: 'Sector 15, Noida',
        city: 'Noida',
        state: 'Uttar Pradesh',
        pincode: '201301',
        coordinates: { lat: 28.5355, lng: 77.3910 },
        lastDonationDate: '2024-09-15',
        isAvailable: true,
        donationCount: 12,
        registrationDate: '2020-03-15',
        idProof: 'Aadhaar',
        verified: true,
        emergencyContact: '9876543211',
    },
    {
        id: '2',
        name: 'Priya Sharma',
        age: 25,
        gender: 'Female',
        bloodGroup: 'A+',
        phone: '9876543220',
        email: 'priya.sharma@email.com',
        address: 'Connaught Place, New Delhi',
        city: 'New Delhi',
        state: 'Delhi',
        pincode: '110001',
        coordinates: { lat: 28.6139, lng: 77.2090 },
        lastDonationDate: '2024-10-20',
        isAvailable: true,
        donationCount: 8,
        registrationDate: '2021-06-10',
        idProof: 'Driving License',
        verified: true,
        emergencyContact: '9876543221',
    },
    {
        id: '3',
        name: 'Amit Patel',
        age: 32,
        gender: 'Male',
        bloodGroup: 'B+',
        phone: '9876543230',
        email: 'amit.patel@email.com',
        address: 'Satellite, Ahmedabad',
        city: 'Ahmedabad',
        state: 'Gujarat',
        pincode: '380015',
        coordinates: { lat: 23.0225, lng: 72.5714 },
        lastDonationDate: '2024-08-05',
        isAvailable: true,
        donationCount: 15,
        registrationDate: '2019-01-20',
        idProof: 'Passport',
        verified: true,
        emergencyContact: '9876543231',
    },
    {
        id: '4',
        name: 'Sneha Reddy',
        age: 29,
        gender: 'Female',
        bloodGroup: 'AB+',
        phone: '9876543240',
        email: 'sneha.reddy@email.com',
        address: 'Banjara Hills, Hyderabad',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500034',
        coordinates: { lat: 17.4065, lng: 78.4772 },
        lastDonationDate: '2024-11-01',
        isAvailable: false,
        donationCount: 6,
        registrationDate: '2022-03-12',
        idProof: 'Aadhaar',
        verified: true,
        emergencyContact: '9876543241',
    },
    {
        id: '5',
        name: 'Vikram Singh',
        age: 35,
        gender: 'Male',
        bloodGroup: 'O-',
        phone: '9876543250',
        email: 'vikram.singh@email.com',
        address: 'Koramangala, Bangalore',
        city: 'Bangalore',
        state: 'Karnataka',
        pincode: '560034',
        coordinates: { lat: 12.9352, lng: 77.6245 },
        lastDonationDate: '2024-07-22',
        isAvailable: true,
        donationCount: 20,
        registrationDate: '2018-05-08',
        idProof: 'Voter ID',
        verified: true,
        emergencyContact: '9876543251',
    },
    {
        id: '6',
        name: 'Anjali Mehta',
        age: 27,
        gender: 'Female',
        bloodGroup: 'A-',
        phone: '9876543260',
        email: 'anjali.mehta@email.com',
        address: 'Andheri West, Mumbai',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400058',
        coordinates: { lat: 19.1136, lng: 72.8697 },
        lastDonationDate: '2024-09-30',
        isAvailable: true,
        donationCount: 10,
        registrationDate: '2020-11-25',
        idProof: 'Aadhaar',
        verified: true,
        emergencyContact: '9876543261',
    },
    {
        id: '7',
        name: 'Rahul Verma',
        age: 30,
        gender: 'Male',
        bloodGroup: 'B-',
        phone: '9876543270',
        email: 'rahul.verma@email.com',
        address: 'Salt Lake, Kolkata',
        city: 'Kolkata',
        state: 'West Bengal',
        pincode: '700091',
        coordinates: { lat: 22.5726, lng: 88.3639 },
        lastDonationDate: '2024-06-18',
        isAvailable: true,
        donationCount: 14,
        registrationDate: '2019-08-14',
        idProof: 'PAN Card',
        verified: true,
        emergencyContact: '9876543271',
    },
    {
        id: '8',
        name: 'Kavita Nair',
        age: 26,
        gender: 'Female',
        bloodGroup: 'AB-',
        phone: '9876543280',
        email: 'kavita.nair@email.com',
        address: 'Kakkanad, Kochi',
        city: 'Kochi',
        state: 'Kerala',
        pincode: '682030',
        coordinates: { lat: 10.0014, lng: 76.3472 },
        lastDonationDate: '2024-10-10',
        isAvailable: false,
        donationCount: 5,
        registrationDate: '2022-07-19',
        idProof: 'Driving License',
        verified: true,
        emergencyContact: '9876543281',
    },
];

// Mock donation history
export const mockDonationHistory = {
    '1': [
        { id: 'h1', date: '2024-09-15', location: 'City Hospital, Noida', bloodUnits: 1 },
        { id: 'h2', date: '2024-06-10', location: 'Red Cross Center, Delhi', bloodUnits: 1 },
        { id: 'h3', date: '2024-03-05', location: 'Apollo Hospital, Noida', bloodUnits: 1 },
    ],
    '2': [
        { id: 'h4', date: '2024-10-20', location: 'AIIMS, New Delhi', bloodUnits: 1 },
        { id: 'h5', date: '2024-07-15', location: 'Max Hospital, Delhi', bloodUnits: 1 },
    ],
};

// Mock hospital requests
export const mockHospitalRequests = [
    {
        id: 'r1',
        hospitalName: 'AIIMS Delhi',
        bloodGroup: 'O+',
        unitsNeeded: 5,
        urgency: 'Critical',
        requestDate: '2024-12-04',
        contactPerson: 'Dr. Sharma',
        contactPhone: '9876501234',
        address: 'Ansari Nagar, New Delhi',
        coordinates: { lat: 28.5672, lng: 77.2100 },
        status: 'Active',
    },
    {
        id: 'r2',
        hospitalName: 'Fortis Hospital',
        bloodGroup: 'A+',
        unitsNeeded: 3,
        urgency: 'High',
        requestDate: '2024-12-04',
        contactPerson: 'Dr. Patel',
        contactPhone: '9876501235',
        address: 'Sector 62, Noida',
        coordinates: { lat: 28.6139, lng: 77.3648 },
        status: 'Active',
    },
    {
        id: 'r3',
        hospitalName: 'Apollo Hospital',
        bloodGroup: 'B-',
        unitsNeeded: 2,
        urgency: 'Medium',
        requestDate: '2024-12-03',
        contactPerson: 'Dr. Kumar',
        contactPhone: '9876501236',
        address: 'Sarita Vihar, Delhi',
        coordinates: { lat: 28.5355, lng: 77.2910 },
        status: 'Active',
    },
];

// Blood groups
export const bloodGroups = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];

// Indian states
export const indianStates = [
    'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
    'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
    'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
    'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
    'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
    'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Puducherry', 'Chandigarh',
];

// ID Proof types
export const idProofTypes = [
    'Aadhaar Card',
    'PAN Card',
    'Driving License',
    'Passport',
    'Voter ID',
];

// Translations
export const translations = {
    en: {
        appName: 'BloodLife',
        tagline: 'Connecting Lives, One Drop at a Time',
        home: 'Home',
        search: 'Search Donors',
        register: 'Register',
        dashboard: 'Dashboard',
        hospitals: 'Hospital Requests',
        about: 'About',
        contact: 'Contact',
        login: 'Login',
        logout: 'Logout',
        donate: 'Donate Blood',
        findDonor: 'Find a Donor',
        becomeADonor: 'Become a Donor',
        emergencyRequest: 'Emergency Blood Request',
        bloodGroup: 'Blood Group',
        location: 'Location',
        distance: 'Distance',
        search: 'Search',
        available: 'Available',
        notAvailable: 'Not Available',
        viewProfile: 'View Profile',
        contactDonor: 'Contact Donor',
        eligibleIn: 'Eligible in',
        days: 'days',
    },
    hi: {
        appName: 'ब्लडलाइफ',
        tagline: 'जीवन जोड़ना, एक बूंद एक समय में',
        home: 'होम',
        search: 'दाताओं को खोजें',
        register: 'पंजीकरण',
        dashboard: 'डैशबोर्ड',
        hospitals: 'अस्पताल अनुरोध',
        about: 'के बारे में',
        contact: 'संपर्क',
        login: 'लॉगिन',
        logout: 'लॉगआउट',
        donate: 'रक्तदान करें',
        findDonor: 'दाता खोजें',
        becomeADonor: 'दाता बनें',
        emergencyRequest: 'आपातकालीन रक्त अनुरोध',
        bloodGroup: 'रक्त समूह',
        location: 'स्थान',
        distance: 'दूरी',
        search: 'खोजें',
        available: 'उपलब्ध',
        notAvailable: 'उपलब्ध नहीं',
        viewProfile: 'प्रोफ़ाइल देखें',
        contactDonor: 'दाता से संपर्क करें',
        eligibleIn: 'में पात्र',
        days: 'दिन',
    },
};
